### ISSUE TITLE
Recherche TB 1825: Pears aromatische Creme

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#170]
S. 67: „Um die bäurische Röthe (vulgar Red), welche die natürliche Schönheit verdunkelt etc., wegzubringen und auszulöschen (obliterate), wird **Pears aromatische Creme** (cream) als ein Gegenstand von zu hoher Wichtigkeit anempfohlen, [...]".

**Comment by vrukavina** [comment]
@ChristopherZoller-Blundell Darf ich dich um Hilfe bitten? Ich könnte wetten, dass du auch hierzu etwas Spannendes zu finden weisst.

**Comment by ChristopherZoller-Blundell** [comment]
Ich glaube, er bezieht sich hier auf die Seifenmarke "Pears". 

"Andrew Pears, the son of a farmer, was born around 1770 in Cornwall and moved from his native Mevagissey to London around 1787. He completed his apprenticeship in 1789, established a barber's shop in Gerrard Street in Soho and began to produce cosmetic products. At that time, Soho was a high-end residential area, and Pears' clientele included many wealthy socialites who took pride in their appearance. The fashion among the wealthy of the period was to have pristine white complexions; tanned faces were associated with those who laboured outdoors. Pears found that his powders and creams were frequently being used to cover up damage caused by the harshness of the soaps and other beauty products that were in general use at the time, many of which contained arsenic or lead. Pears began to experiment with soap purification and eventually managed to produce a gentle soap based on glycerine and other natural products. The clarity of the soap gave it a novel transparent appearance, which provided a marketing advantage. To add to the appeal, **Pears gave the soap an aroma reminiscent of an English garden.** It was first sold in London in **1807**."

https://en.wikipedia.org/wiki/Pears_(soap)

**Comment by vrukavina** [comment]
Genial! Danke!
