### ISSUE TITLE
link to page on e-rara.ch in english versions

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#518]
I just noted that the pop-up with the page number and link to e-rara.ch in the english versions reads "Seite xx" instead of "page xx". Please change to english. Thank you

<img width="918" alt="Bildschirmfoto 2023-12-06 um 21 17 31" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/7cc565d0-061f-4c28-95a1-f88019f033ee">

**Comment by feggimann** [comment]
@HelenaSabel thank you. Can you please use lower case p for page?

**Comment by HelenaSabel** [comment]
With the lower case p, I thought it didn’t looked very legible because of the underline. 

![image](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/8516387/7b4e6591-ef2d-4d9d-892c-9b309dd2da9f)

How about without being underline? I personally think that with the symbol for the external link it’s already clear that it’s a link without the need of additional formatting. What do you think @feggimann?

![image](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/8516387/9c2af02e-addd-444f-8bdd-2891f5deec51)

**Comment by feggimann** [comment]
yes, this looks fine without the underline, also in German. Thank you
